services:
  - type: web
    name: ssf
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask db upgrade && flask seed-admin && gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: FLASK_APP
        value: run.py
      - key: RATELIMIT_STORAGE_URI
        value: memory://
      - key: INIT_ADMIN_EMAIL
        sync: false
      - key: INIT_ADMIN_PASSWORD
        sync: false
